### ISSUE TITLE
Corrections for linux and codepage

### ISSUE THREAD

**Issue by tatue64** [alexander-pastukhov/eyelink_reader#1]
I tested the program on linux and after some changes, it works great. Thanks for your work.

I made the following adjustments in **edffile.py**:

1. Change `edfapi_filename` in function `_load_library()`  to the correct library path under linux (as also stated in the documentation)

```python
        if platform.system() == "Linux":
            edfapi_filename = "libedfapi.so"
```
4. Change the platform specific searchpath

```python
 :
        elif platform.system() == "Darwin":
            paths_to_try.append("/Library/Frameworks/")
        elif platform.system() == "Linux":
            paths_to_try.insert(0,"/usr/lib/x86_64-linux-gnu/")

:
```
and **edfdata.py**:

1. The data read from file are formatted with codec "latin-1" and not "utf-8", thus you need to decode from "latin-1". Without this adjustment strings containing, for example, umlaut characters are lost (NaN):

In class EDF_FEVENT(structure), member function `__getitem__(self, field_name)`

```python
       import codecs 
:
       if field_name == "message":
            # special case of LSTRING
            if getattr(self, field_name) and getattr(self, field_name).contents.len > 0 and len(getattr(self, field_name).contents.c) > 0:
                try:
                    message_str = codecs.decode(getattr(self, field_name).contents.c, "latin-1")                    
                except UnicodeDecodeError:
                    message_str = ""
                return message_str
            else:
```

**Comment by alexander-pastukhov** [comment]
@tatue64 thanks!!! Do you want to create a pull request or should I just copy-paste myself?

**Comment by tatue64** [comment]
> @tatue64 thanks!!! Do you want to create a pull request or should I just copy-paste myself?

Just copy these small changes by yourself

**Comment by alexander-pastukhov** [comment]
@tatue64 Thanks again!
